version: '3.8'

services:
  ai-automation:
    build:
      context: ./tools/ai-automation
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-sebastian}_ai_automation
    environment:
      VERSION: ${VERSION}
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV:-development}
      NODE_ENV: ${APP_ENV:-development}
      HOST: ${HOST}
      DISPLAY: :99
    ports:
      - "4000:4000"
    volumes:
      - ./tools/ai-automation:/usr/src/app
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      - app-network

networks:
  app-network:
    name: ${APP_NAME:-sebastian}_app-network
    driver: bridge
